FROM openjdk:17-ea-jdk-oracle
MAINTAINER sagorsarker
WORKDIR /app
COPY ./target/currency-conversion-service-0.0.1-SNAPSHOT.jar /app
CMD ["java", "-jar", "currency-conversion-service-0.0.1-SNAPSHOT.jar"]
