FROM openjdk:17-ea-jdk-oracle
MAINTAINER sagorsarker
WORKDIR /app
COPY ./target/currency-exchange-service-0.0.1-SNAPSHOT.jar /app
EXPOSE 8000
CMD ["java", "-jar", "currency-exchange-service-0.0.1-SNAPSHOT.jar"]
